# Numpy

- numpy array의 생김새

In [1]:
import numpy as np

In [4]:
array1 = np.array([2,3,5,7,11,13,17,19,23,29,31])

In [5]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [6]:
type(array1)

numpy.ndarray

In [10]:
array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [11]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
# 행렬을 확인하기 위해 shape
array2.shape

(3, 4)

In [15]:
#개수를 확인하기 위해 size
array2.size

12

# 균일한 값으로 생성

- numpy 모듈의 full 메소드를 사용하면, 모든 값이 같은 numpy array를 생성할 수 있습니다.

In [18]:
array1 = np.full(6, 7)
    
print(array1)

[7 7 7 7 7 7]


# 모든 값이 1인 numpy array 생성

- 모든 값이 1인 numpy array를 생성하는 것도 비슷합니다. zeros 메소드 대신 ones를 사용하면 됩니다.

In [19]:
array1 = np.full(6, 1)
array2 = np.ones(6, dtype=int)
    
print(array1)
print()
print(array2)

[1 1 1 1 1 1]

[1 1 1 1 1 1]


# 랜덤한 값들로 생성

- 어쩔 때는 임의의 값들로 배열을 생성시키고 싶습니다. 그럴 때는 numpy의 random 모듈의 random 함수를 사용하면 됩니다.
<br>

- numpy 모듈 안에 random이라는 모듈이 있고, 그 안에 또 random이라는 함수가 있는 겁니다!

In [20]:
array1 = np.random.random(6)
array2 = np.random.random(6)
    
print(array1)
print()
print(array2)

[0.40551247 0.85282045 0.95821525 0.12900557 0.08332966 0.31851713]

[0.14627448 0.98309631 0.81332807 0.93805798 0.94672571 0.59154538]


# 연속된 값들이 담긴 numpy array 생성
- numpy 모듈의 arange 함수를 사용하면 연속된 값들이 담겨 있는 numpy array를 생성할 수 있습니다.
<br>

- arange 함수는 파이썬의 기본 함수인 range와 굉장히 비슷한 원리로 동작하는데요. 파라미터가 1개인 경우, 2개인 경우, 3개인 경우 모두 살펴봅시다.

### 파라미터 1개
- arange(m)을 하면 0부터 m-1까지의 값들이 담긴 numpy array가 리턴됩니다.

In [23]:
array1 = np.arange(6)
print(array1)

[0 1 2 3 4 5]


### 파라미터 2개
- arange(n, m)을 하면 n부터 m-1까지의 값들이 담긴 numpy array가 리턴됩니다.

In [25]:
array1 = np.arange(2, 7)
print(array1)

[2 3 4 5 6]


### 파라미터 3개
- arange(n, m, s)를 하면 n부터 m-1까지의 값들 중 간격이 s인 값들이 담긴 numpy array가 리턴됩니다.

In [27]:
array1 = np.arange(3, 17, 3)
print(array1)

[ 3  6  9 12 15]
