In [1]:
import numpy as np

In [12]:
array1 = np.array([2,3,5,7,11,13,17,19,23,29,31])

In [4]:
array1[0]

2

In [5]:
array1[2]

5

In [6]:
array1[-1]

31

In [8]:
array1[-2]

29

In [13]:
array1[[1,3,4]]

array([ 3,  7, 11])

In [14]:
array2=np.array([2,1,3])

In [15]:
array1[array2]

array([5, 3, 7])

In [16]:
array1[2:7]

array([ 5,  7, 11, 13, 17])

In [19]:
# 0번 부터 시작하고 싶으면 앞을 비워도 된다.
array1[:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [20]:
# 2번 index 부터 시작하고 싶으면 앞에 2를 붙인다.
array1[2:]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

In [21]:
# 하나씩 건너뛰어서 세고 싶으면 3번째 자리에 n 만큼 수 작성
array1[2:11:2]

array([ 5, 11, 17, 23, 31])

In [22]:
# 하나씩 건너뛰어서 세고 싶으면 3번째 자리에 n 만큼 수 작성
array1[2:11:3]

array([ 5, 13, 23])