In [1]:
import numpy as np

In [9]:
array1 = np.array([0,1,2,3,4,5,6])
array2 = np.array([0,1,2,3,4,5,6,7,8])

array1 = np.arange(10)
array2 = np.arange(10,20)

In [3]:
array1

array([0, 1, 2, 3, 4, 5, 6])

In [4]:
array1 + 1

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12])

In [7]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [8]:
array1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)

In [10]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [12]:
array1 * array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [13]:
array1 / array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [14]:
array1 ** array2

array([          0,           1,        4096,     1594323,   268435456,
         452807053,  -683606016, -2094633337,           0,  -400556711],
      dtype=int32)