# numpy "Num + Py" (Numerical Python)
- C언어로 구현된 파이썬 라이브러리로써, 고성능의 수치계산을 위해 제작되었습니다. 
- Numpy는 벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공합니다.

In [2]:
import numpy as np

In [3]:
A = np. array([
    [1,-1,2],
    [3,2,2],
    [4,1,2],
    [7,5,6]
    ])

In [4]:
print(A)

[[ 1 -1  2]
 [ 3  2  2]
 [ 4  1  2]
 [ 7  5  6]]


In [5]:
# zeros는 () 괄호를 한 번 사용해야함
C = np.random.rand(3,5)
print(C)

[[0.31434607 0.39847094 0.75880884 0.59112309 0.71101781]
 [0.83301886 0.1907396  0.08479004 0.15859698 0.55082831]
 [0.46052192 0.05513294 0.22569441 0.10159355 0.57149507]]



In [6]:
# zeros는 () 괄호를 한 번더 사용해야함
D = np.zeros((2,4))
print(D)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
print(A[0][0])
print(A[0][1])

1
-1
