# Numpy 행렬 연산

In [1]:
import numpy as np

In [3]:
A = np.array([
    [1,-1,2],
    [3,2,2],
    [4,1,2]
])

B = np.random.rand(3,3)

In [4]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [5]:
B

array([[0.41361703, 0.28667377, 0.08371179],
       [0.92263224, 0.98734619, 0.01937489],
       [0.08494315, 0.18694024, 0.82422653]])

In [6]:
A+B

array([[ 1.41361703, -0.71332623,  2.08371179],
       [ 3.92263224,  2.98734619,  2.01937489],
       [ 4.08494315,  1.18694024,  2.82422653]])

In [7]:
5 * A

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [8]:
A*5

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [9]:
np.dot(A, B)

array([[-0.33912892, -0.32679194,  1.71278996],
       [ 3.25600185,  3.20859418,  1.93833823],
       [ 2.74698664,  2.50792176,  2.00267512]])

In [10]:
A @ B

array([[-0.33912892, -0.32679194,  1.71278996],
       [ 3.25600185,  3.20859418,  1.93833823],
       [ 2.74698664,  2.50792176,  2.00267512]])

In [11]:
A @ B + A + 2 + B

array([[3.07448811, 0.95988183, 5.79650176],
       [9.17863409, 8.19594037, 5.95771312],
       [8.83192978, 5.694862  , 6.82690166]])