# 행렬 종류
- 전치 행렬 (Transposed Matrix)
    <ol>
        <li>행렬의 열과 행을 바꾸는 것</li>
        <br>
        <li>A = $\begin{bmatrix}
            1&2&1\\3&2&2\\ \end{bmatrix}
        $ $\Longrightarrow$ A$^T$ = $\begin{bmatrix}
            1&3\\2&2\\1&2\\ \end{bmatrix}
        $</li>
    </ol>
    <br>

- 단위 행렬 (Identity Matrix)
    <ol>
        <li>단위 행렬은 정사각형</li>
        <br>
        <li>A * I = A</li>
        <br>
        <li>A = $\begin{bmatrix}
            3&4\\1&2\\ \end{bmatrix}$ $,$ $ $I = $\begin{bmatrix}
            1&0\\0&1\\ \end{bmatrix}$        
         <br><br>
         $\Longrightarrow$ A*I = $\begin{bmatrix}
            3&4\\1&2\\ \end{bmatrix}
        $</li>
    </ol>
    <br>

- 역행렬 (Inverse Matrix)
    <ol>
        <li>곱 했을경우 1이 나오도록 하는 수</li>
        <br>
        <li>역행렬은 정사각형이여야 하며, 모든 행렬에 역행렬이 있는 것은 아니다.</li>
        <br>
        <li>A = $\begin{bmatrix}
            3&4\\1&2\\ \end{bmatrix}$ $,$ $ $A$^{-1}$ = $\begin{bmatrix}
            1&-2\\-\frac{1}{2}&\frac{3}{2}\\ \end{bmatrix}$        
         <br><br>
         $\Longrightarrow$ A*A$^{-1}$ = $\begin{bmatrix}
            1&0\\0&1\\ \end{bmatrix}
        $</li>
    
    </ol>
    

In [1]:
import numpy as np

In [2]:
A = np.array([
    [1,-1,2],
    [3,2,2],
    [4,1,2]
])

In [4]:
A_tranpose = A.T

In [5]:
A_tranpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [8]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
A @ I

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

#### 리니어 알지브라 (피 인브 함수) A의 역행렬을 구하라

In [12]:
A_inverse = np.linalg.pinv(A)
A_inverse

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

##### 뒤의 소수 0은 무수히 많은 것인데 컴퓨터가 표현하기 어려워 오차가 생기는 것 --> 15, 16 

In [13]:
A @ A_inverse

array([[ 1.00000000e+00,  6.66133815e-16, -1.11022302e-15],
       [-2.22044605e-16,  1.00000000e+00, -6.66133815e-16],
       [ 0.00000000e+00,  2.22044605e-16,  1.00000000e+00]])